# Render Configuration for Hackathon Platform
services:
  - type: web
    name: hackathon-platform
    env: node
    region: oregon
    plan: starter
    buildCommand: npm run build:render
    installCommand: npm ci
    startCommand: npm start
    healthCheckPath: /
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: hackathon-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: NEXTAUTH_URL
        value: https://hackathon-platform.onrender.com
      - key: NEXTAUTH_SECRET
        generateValue: true

databases:
  - name: hackathon-db
    databaseName: hackathon_production
    user: hackathon_user
    region: oregon
    plan: starter
